### ISSUE TITLE
Fix zfighting on annunciator windows

### ISSUE THREAD

**Issue by watchful5406** [OpenLWR/OpenLWR#23]

**Comment by RedstoneParkour** [comment]
some potential solutions (might look into them later):

- adjust the near and far plane to more reasonable values
- upgrade to godot 4.3 to get reverse z [(blog post)](https://godotengine.org/article/introducing-reverse-z/)
- use textures instead of labels (not sure if this is applicable)

**Comment by SakuruWasTaken** [comment]
we should upgrade to 4.3 anyways as it offers some performance benefits, if it can also help to solve this problem that's good

**Comment by watchful5406** [comment]
Fixed by updating to godot 4.3
