### ISSUE TITLE
[Arch Linux + Wayland] "Pan Mode" option doesn't do anything

### ISSUE THREAD

**Issue by RadiantCorium** [OpenLWR/OpenLWR#28]
Camera acts the same with the toggle on as it does without it.

**Comment by watchful5406** [comment]
will take a look in 1-2hrs

**Comment by SakuruWasTaken** [comment]
what's your DE?

**Comment by RadiantCorium** [comment]
> what's your DE?

Hyprland
Also haven't tested how well it works on a X11 environment.

**Comment by watchful5406** [comment]
> Camera acts the same with the toggle on as it does without it.

I think this happened a while ago. Probably a failed attempt at a bugfix. I should be able to fix this as soon as i'm home

**Comment by watchful5406** [comment]
Probably fixed.
