### ISSUE TITLE
Character collision (and animations)

### ISSUE THREAD

**Issue by creativforce** [OpenLWR/OpenLWR#30]
Whenever two characters collide, it plays the next gif:
![biden-bike](https://github.com/user-attachments/assets/9ea28db4-69ab-4e2c-ba2c-ab0c1c5efa3a)

**Comment by SakuruWasTaken** [comment]
no

**Comment by watchful5406** [comment]
wait

**Comment by maklecule** [comment]
"no"

**Comment by watchful5406** [comment]
![biden](https://github.com/user-attachments/assets/ae593bb1-6ee8-47ba-979c-e690da454d49)

**Comment by amarkowski999** [comment]
aggre
